# Generated by Django 5.0.1 on 2024-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_remove_borrower_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
