# Generated by Django 5.0.1 on 2024-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_borrower_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
