# Generated by Django 5.0.1 on 2024-02-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_alter_borrower_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity_avilable',
            new_name='quantity_available',
        ),
    ]
