# Generated by Django 5.0.1 on 2024-02-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_rename_book_transaction_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='return_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
